# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
    - image: leeroy-app
      context: leeroy-app
deploy:
  kustomize:
    paths:
      - leeroy-app/kubernetes/dev
profiles:
- name: qa
  deploy:
    kustomize:
      paths:
        - leeroy-app/kubernetes/qa
- name: prod
  deploy:
    kustomize:
      paths:
        - leeroy-app/kubernetes/prod
