# NOT TO BE USED IN THE 'CONTINUOUS DELIVERY ON GCP' DEMO
# IN THAT CASE THE TEST CLUSTER WILL BE A LOCAL MINIKUBE

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: test
description: Test Cluster (GCP)
gke:
  cluster: projects/galloro-demos/locations/europe-west1-b/clusters/test-cluster
